export {
	$canGoNext,
	$canGoPrev,
	$credentials,
	$currentStep,
	$error,
	$isLoading,
	$profileData,
	$role,
	$selectedSkills,
	addSkill,
	addSkillsFx,
	nextStep,
	prevStep,
	registerUserFx,
	removeSkill,
	resetOnboarding,
	setCredentials,
	setCurrentStep,
	setProfileData,
	setRole,
	updateProfileFx,
	updateSkillLevel,
} from './model'
export type {
	OnboardingState,
	OnboardingStep,
	ProfileData,
	StepValidation,
	UpdateSkillLevel,
} from './types'
