/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Account {
	access_token: string | null
	account_id: string
	created_at: Generated<Timestamp | null>
	expires_at: Timestamp | null
	id: Generated<string>
	password: string | null
	provider_id: string
	refresh_token: string | null
	updated_at: Generated<Timestamp | null>
	user_id: string
}

export interface KnexMigrations {
	batch: number | null
	id: Generated<number>
	migration_time: Timestamp | null
	name: string | null
}

export interface KnexMigrationsLock {
	index: Generated<number>
	is_locked: number | null
}

export interface Sessions {
	created_at: Generated<Timestamp | null>
	expires_at: Timestamp
	id: Generated<string>
	ip_address: string | null
	user_agent: string | null
	user_id: string
}

export interface Skills {
	category: string | null
	created_at: Generated<Timestamp | null>
	id: Generated<string>
	name: string
}

export interface UserProfiles {
	avatar_url: string | null
	bio: string | null
	company_name: string | null
	company_role: string | null
	created_at: Generated<Timestamp | null>
	id: Generated<string>
	name: string | null
	search_vector: Generated<string | null>
	updated_at: Generated<Timestamp | null>
	user_id: string
}

export interface Users {
	created_at: Generated<Timestamp | null>
	email: string
	email_verified: Generated<boolean | null>
	email_verified_at: Timestamp | null
	id: Generated<string>
	image: string | null
	name: string | null
	password_hash: string | null
	role: string
	updated_at: Generated<Timestamp | null>
}

export interface UserSkills {
	created_at: Generated<Timestamp | null>
	id: Generated<string>
	proficiency_level: string | null
	skill_id: string
	user_id: string
}

export interface Verification {
	created_at: Generated<Timestamp | null>
	expires_at: Timestamp
	id: Generated<string>
	identifier: string
	value: string
}

export interface DB {
	account: Account
	knex_migrations: KnexMigrations
	knex_migrations_lock: KnexMigrationsLock
	sessions: Sessions
	skills: Skills
	user_profiles: UserProfiles
	user_skills: UserSkills
	users: Users
	verification: Verification
}
