/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
	[x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Accounts {
	accessToken: string | null
	accessTokenExpiresAt: Timestamp | null
	accountId: string
	createdAt: Generated<Timestamp>
	id: string
	idToken: string | null
	password: string | null
	providerId: string
	refreshToken: string | null
	refreshTokenExpiresAt: Timestamp | null
	scope: string | null
	updatedAt: Timestamp
	userId: string
}

export interface FreelancerProfiles {
	availability: string | null
	created_at: Generated<Timestamp | null>
	experience: string | null
	hourly_rate: number | null
	id: Generated<string>
	specialization: string | null
	updated_at: Generated<Timestamp | null>
	user_id: string
}

export interface KnexMigrations {
	batch: number | null
	id: Generated<number>
	migration_time: Timestamp | null
	name: string | null
}

export interface KnexMigrationsLock {
	index: Generated<number>
	is_locked: number | null
}

export interface PortfolioItems {
	caption: string | null
	category: string | null
	created_at: Generated<Timestamp | null>
	description: string | null
	freelancer_profile_id: string
	id: Generated<string>
	media_height: number | null
	media_type: string | null
	media_url: string
	media_width: number | null
	title: string
	tools_used: Json | null
	updated_at: Generated<Timestamp | null>
}

export interface Sessions {
	createdAt: Generated<Timestamp>
	expiresAt: Timestamp
	id: string
	ipAddress: string | null
	token: string
	updatedAt: Timestamp
	userAgent: string | null
	userId: string
}

export interface Skills {
	category: string | null
	created_at: Generated<Timestamp | null>
	id: string
	legacy_id: string | null
	name: string
}

export interface UserProfiles {
	avatar_url: string | null
	bio: string | null
	company_name: string | null
	company_role: string | null
	created_at: Generated<Timestamp | null>
	id: string
	name: string | null
	search_vector: Generated<string | null>
	updated_at: Generated<Timestamp | null>
	user_id: string
}

export interface Users {
	createdAt: Generated<Timestamp>
	email: string
	emailVerified: boolean
	id: string
	image: string | null
	name: string
	role: string
	updatedAt: Generated<Timestamp>
}

export interface UserSkills {
	created_at: Generated<Timestamp | null>
	id: string
	legacy_skill_id: string | null
	proficiency_level: string | null
	skill_id: string
	user_id: string
}

export interface Verifications {
	createdAt: Generated<Timestamp>
	expiresAt: Timestamp
	id: string
	identifier: string
	updatedAt: Generated<Timestamp>
	value: string
}

export interface DB {
	accounts: Accounts
	freelancer_profiles: FreelancerProfiles
	knex_migrations: KnexMigrations
	knex_migrations_lock: KnexMigrationsLock
	portfolio_items: PortfolioItems
	sessions: Sessions
	skills: Skills
	user_profiles: UserProfiles
	user_skills: UserSkills
	users: Users
	verifications: Verifications
}
